AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sms_handler

  Sample SAM Template for sms_send

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:
  SmsHandleInboundFunction:  # Renamed from HelloWorldFunction to SmsHandleInboundFunction
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handle_sms_inbound/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: 
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:

  SmsHandleInboundFunction:  # Renamed from HelloWorldFunction to SmsHandleInboundFunction
    Description: "SMS Handle Inbound Lambda Function ARN"
    Value: !GetAtt SmsHandleInboundFunction.Arn

  SmsHandleInboundFunctionIamRole:  # Renamed from HelloWorldFunctionIamRole to SmsHandleInboundFunctionIamRole
    Description: "Implicit IAM Role created for SMS Handle Inbound function"
    Value: !GetAtt SmsHandleInboundFunctionRole.Arn